#!/bin/bash

PKG_NAME="istatserver"
INST_DIR="/tmp/_${PKG_NAME}"
PKG_DIR="/tmp/_${PKG_NAME}_pkg"
PKG_DST="/image/packages"

PrepareDirs() {
    for dir in $INST_DIR $PKG_DIR; do
        rm -rf "$dir"
    done
    for dir in $INST_DIR $PKG_DIR $PKG_DST; do
        mkdir -p "$dir"
    done
}

SetupPackageFiles() {
    make install
    ./INFO.sh > INFO
    cp INFO "${PKG_DIR}"
    cp -r scripts/ "${PKG_DIR}"
    cp -av PACKAGE_ICON*.PNG "${PKG_DIR}"
}

MakePackage() {
    source /pkgscripts/include/pkg_util.sh
    pkg_make_package $INST_DIR $PKG_DIR
    pkg_make_spk $PKG_DIR $PKG_DST
}

main() {
    PrepareDirs
    SetupPackageFiles
    MakePackage 
}

main "$@"
